server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: ${CHORDSKED_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
  sql:
    init:
      schema-locations: classpath:db/h2/schema.sql
  datasource:
    url: jdbc:h2:mem:chordsked_prerelease;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
